//
// Generated file, do not edit! Created by nedtool 5.4 from stack/phy/packet/cbr.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CBR_M_H
#define __CBR_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/phy/packet/cbr.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Cbr
 * {
 *     double cbr;
 * }
 * </pre>
 */
class Cbr : public ::omnetpp::cPacket
{
  protected:
    double cbr;

  private:
    void copy(const Cbr& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Cbr&);

  public:
    Cbr(const char *name=nullptr, short kind=0);
    Cbr(const Cbr& other);
    virtual ~Cbr();
    Cbr& operator=(const Cbr& other);
    virtual Cbr *dup() const override {return new Cbr(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getCbr() const;
    virtual void setCbr(double cbr);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Cbr& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Cbr& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CBR_M_H

