//
// Generated file, do not edit! Created by nedtool 5.4 from stack/phy/packet/LteFeedbackPkt.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __LTEFEEDBACKPKT_M_H
#define __LTEFEEDBACKPKT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/phy/packet/LteFeedbackPkt.msg:10</tt> by nedtool.
 * <pre>
 * packet LteFeedbackPkt
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 * }
 * </pre>
 *
 * LteFeedbackPkt_Base is only useful if it gets subclassed, and LteFeedbackPkt is derived from it.
 * The minimum code to be written for LteFeedbackPkt is the following:
 *
 * <pre>
 * class LteFeedbackPkt : public LteFeedbackPkt_Base
 * {
 *   private:
 *     void copy(const LteFeedbackPkt& other) { ... }

 *   public:
 *     LteFeedbackPkt(const char *name=nullptr, short kind=0) : LteFeedbackPkt_Base(name,kind) {}
 *     LteFeedbackPkt(const LteFeedbackPkt& other) : LteFeedbackPkt_Base(other) {copy(other);}
 *     LteFeedbackPkt& operator=(const LteFeedbackPkt& other) {if (this==&other) return *this; LteFeedbackPkt_Base::operator=(other); copy(other); return *this;}
 *     virtual LteFeedbackPkt *dup() const override {return new LteFeedbackPkt(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from LteFeedbackPkt_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(LteFeedbackPkt)
 * </pre>
 */
class LteFeedbackPkt_Base : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const LteFeedbackPkt_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteFeedbackPkt_Base&);
    // make constructors protected to avoid instantiation
    LteFeedbackPkt_Base(const char *name=nullptr, short kind=0);
    LteFeedbackPkt_Base(const LteFeedbackPkt_Base& other);
    // make assignment operator protected to force the user override it
    LteFeedbackPkt_Base& operator=(const LteFeedbackPkt_Base& other);

  public:
    virtual ~LteFeedbackPkt_Base();
    virtual LteFeedbackPkt_Base *dup() const override {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class LteFeedbackPkt");}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};


#endif // ifndef __LTEFEEDBACKPKT_M_H

