//
// Generated file, do not edit! Created by nedtool 5.4 from stack/phy/packet/SidelinkControlInformation.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SIDELINKCONTROLINFORMATION_M_H
#define __SIDELINKCONTROLINFORMATION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/phy/packet/SidelinkControlInformation.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // Sidelink Control Information (SCI) message, used in LTE Mode 4.
 * //
 * packet SidelinkControlInformation
 * {
 *     unsigned int priority;
 *     unsigned int resourceReservationInterval;
 *     unsigned int frequencyResourceLocation;
 *     unsigned int timeGapRetrans;
 *     unsigned int mcs;
 *     unsigned int oneShotLocation;
 *     unsigned int retransmissionIndex;
 * }
 * </pre>
 */
class SidelinkControlInformation : public ::omnetpp::cPacket
{
  protected:
    unsigned int priority;
    unsigned int resourceReservationInterval;
    unsigned int frequencyResourceLocation;
    unsigned int timeGapRetrans;
    unsigned int mcs;
    unsigned int oneShotLocation;
    unsigned int retransmissionIndex;

  private:
    void copy(const SidelinkControlInformation& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SidelinkControlInformation&);

  public:
    SidelinkControlInformation(const char *name=nullptr, short kind=0);
    SidelinkControlInformation(const SidelinkControlInformation& other);
    virtual ~SidelinkControlInformation();
    SidelinkControlInformation& operator=(const SidelinkControlInformation& other);
    virtual SidelinkControlInformation *dup() const override {return new SidelinkControlInformation(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getPriority() const;
    virtual void setPriority(unsigned int priority);
    virtual unsigned int getResourceReservationInterval() const;
    virtual void setResourceReservationInterval(unsigned int resourceReservationInterval);
    virtual unsigned int getFrequencyResourceLocation() const;
    virtual void setFrequencyResourceLocation(unsigned int frequencyResourceLocation);
    virtual unsigned int getTimeGapRetrans() const;
    virtual void setTimeGapRetrans(unsigned int timeGapRetrans);
    virtual unsigned int getMcs() const;
    virtual void setMcs(unsigned int mcs);
    virtual unsigned int getOneShotLocation() const;
    virtual void setOneShotLocation(unsigned int oneShotLocation);
    virtual unsigned int getRetransmissionIndex() const;
    virtual void setRetransmissionIndex(unsigned int retransmissionIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SidelinkControlInformation& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SidelinkControlInformation& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIDELINKCONTROLINFORMATION_M_H

