//
// Generated file, do not edit! Created by nedtool 5.4 from apps/alert/AlertPacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __ALERTPACKET_M_H
#define __ALERTPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>apps/alert/AlertPacket.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Packet used by the ~AlertSender and ~AlertReceiver modules.
 * //
 * packet AlertPacket
 * {
 *     unsigned int sno;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class AlertPacket : public ::omnetpp::cPacket
{
  protected:
    unsigned int sno;
    ::omnetpp::simtime_t timestamp;

  private:
    void copy(const AlertPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AlertPacket&);

  public:
    AlertPacket(const char *name=nullptr, short kind=0);
    AlertPacket(const AlertPacket& other);
    virtual ~AlertPacket();
    AlertPacket& operator=(const AlertPacket& other);
    virtual AlertPacket *dup() const override {return new AlertPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getSno() const;
    virtual void setSno(unsigned int sno);
    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlertPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlertPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ALERTPACKET_M_H

