//
// Generated file, do not edit! Created by nedtool 5.4 from common/timer/TTimerMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TTIMERMSG_M_H
#define __TTIMERMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
    #include "common/LteCommon.h"

    /**
     * Timer type
     */
    enum TTimerType
    {
       TTSIMPLE, TTMULTI
    };
// }}

/**
 * Class generated from <tt>common/timer/TTimerMsg.msg:25</tt> by nedtool.
 * <pre>
 * packet TTimerMsg
 * {
 *     unsigned int timerId;
 *     unsigned short type \@enum(TTimerType);
 * }
 * </pre>
 */
class TTimerMsg : public ::omnetpp::cPacket
{
  protected:
    unsigned int timerId;
    unsigned short type;

  private:
    void copy(const TTimerMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TTimerMsg&);

  public:
    TTimerMsg(const char *name=nullptr, short kind=0);
    TTimerMsg(const TTimerMsg& other);
    virtual ~TTimerMsg();
    TTimerMsg& operator=(const TTimerMsg& other);
    virtual TTimerMsg *dup() const override {return new TTimerMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getTimerId() const;
    virtual void setTimerId(unsigned int timerId);
    virtual unsigned short getType() const;
    virtual void setType(unsigned short type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TTimerMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TTimerMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TTIMERMSG_M_H

