//
// Generated file, do not edit! Created by nedtool 5.4 from epc/gtp/GtpUserMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __GTPUSERMSG_M_H
#define __GTPUSERMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>epc/gtp/GtpUserMsg.msg:11</tt> by nedtool.
 * <pre>
 * packet GtpUserMsg
 * {
 *     unsigned int teid;
 * }
 * </pre>
 */
class GtpUserMsg : public ::omnetpp::cPacket
{
  protected:
    unsigned int teid;

  private:
    void copy(const GtpUserMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GtpUserMsg&);

  public:
    GtpUserMsg(const char *name=nullptr, short kind=0);
    GtpUserMsg(const GtpUserMsg& other);
    virtual ~GtpUserMsg();
    GtpUserMsg& operator=(const GtpUserMsg& other);
    virtual GtpUserMsg *dup() const override {return new GtpUserMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getTeid() const;
    virtual void setTeid(unsigned int teid);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GtpUserMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GtpUserMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __GTPUSERMSG_M_H

