//
// Generated file, do not edit! Created by nedtool 5.4 from stack/mac/packet/LteHarqFeedback.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __LTEHARQFEEDBACK_M_H
#define __LTEHARQFEEDBACK_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/mac/packet/LteHarqFeedback.msg:11</tt> by nedtool.
 * <pre>
 * packet LteHarqFeedback
 * {
 *     // H-ARQ acid to which this fb is addressed
 *     unsigned char acid;
 *     // H-ARQ cw id to which this fb is addressed
 *     unsigned char cw;
 *     // H-ARQ feedback: true for ACK, false for NACK
 *     bool result;
 *     // Id of the pdu to which the feedback is addressed
 *     long fbMacPduId;
 * }
 * </pre>
 */
class LteHarqFeedback : public ::omnetpp::cPacket
{
  protected:
    unsigned char acid;
    unsigned char cw;
    bool result;
    long fbMacPduId;

  private:
    void copy(const LteHarqFeedback& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteHarqFeedback&);

  public:
    LteHarqFeedback(const char *name=nullptr, short kind=0);
    LteHarqFeedback(const LteHarqFeedback& other);
    virtual ~LteHarqFeedback();
    LteHarqFeedback& operator=(const LteHarqFeedback& other);
    virtual LteHarqFeedback *dup() const override {return new LteHarqFeedback(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned char getAcid() const;
    virtual void setAcid(unsigned char acid);
    virtual unsigned char getCw() const;
    virtual void setCw(unsigned char cw);
    virtual bool getResult() const;
    virtual void setResult(bool result);
    virtual long getFbMacPduId() const;
    virtual void setFbMacPduId(long fbMacPduId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteHarqFeedback& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteHarqFeedback& obj) {obj.parsimUnpack(b);}


#endif // ifndef __LTEHARQFEEDBACK_M_H

