//
// Generated file, do not edit! Created by nedtool 5.4 from stack/rlc/packet/LteRlcDataPdu.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __LTERLCDATAPDU_M_H
#define __LTERLCDATAPDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/rlc/packet/LteRlcDataPdu.msg:18</tt> by nedtool.
 * <pre>
 * //
 * // This is the RLC Data Pdu (base for all RLC modes)
 * // flowing through LTE stack: basically
 * // it contains the fields 
 * // that receiver needs in order to
 * // correctly decode the original packets
 * //
 * packet LteRlcDataPdu
 * {
 *     \@customize(true);
 * }
 * </pre>
 *
 * LteRlcDataPdu_Base is only useful if it gets subclassed, and LteRlcDataPdu is derived from it.
 * The minimum code to be written for LteRlcDataPdu is the following:
 *
 * <pre>
 * class LteRlcDataPdu : public LteRlcDataPdu_Base
 * {
 *   private:
 *     void copy(const LteRlcDataPdu& other) { ... }

 *   public:
 *     LteRlcDataPdu(const char *name=nullptr, short kind=0) : LteRlcDataPdu_Base(name,kind) {}
 *     LteRlcDataPdu(const LteRlcDataPdu& other) : LteRlcDataPdu_Base(other) {copy(other);}
 *     LteRlcDataPdu& operator=(const LteRlcDataPdu& other) {if (this==&other) return *this; LteRlcDataPdu_Base::operator=(other); copy(other); return *this;}
 *     virtual LteRlcDataPdu *dup() const override {return new LteRlcDataPdu(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from LteRlcDataPdu_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(LteRlcDataPdu)
 * </pre>
 */
class LteRlcDataPdu_Base : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const LteRlcDataPdu_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRlcDataPdu_Base&);
    // make constructors protected to avoid instantiation
    LteRlcDataPdu_Base(const char *name=nullptr, short kind=0);
    LteRlcDataPdu_Base(const LteRlcDataPdu_Base& other);
    // make assignment operator protected to force the user override it
    LteRlcDataPdu_Base& operator=(const LteRlcDataPdu_Base& other);

  public:
    virtual ~LteRlcDataPdu_Base();
    virtual LteRlcDataPdu_Base *dup() const override {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class LteRlcDataPdu");}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};


#endif // ifndef __LTERLCDATAPDU_M_H

