//
// Generated file, do not edit! Created by nedtool 5.4 from apps/voip/VoipPacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __VOIPPACKET_M_H
#define __VOIPPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>apps/voip/VoipPacket.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // Packet used by the ~VoPSender and ~VoIPReceiver modules.
 * //
 * packet VoipPacket
 * {
 *     unsigned int IDtalk;
 *     unsigned int nframes;
 *     unsigned int IDframe;
 *     simtime_t timestamp;
 *     simtime_t arrivalTime;
 *     simtime_t playoutTime;
 *     unsigned int size;
 * }
 * </pre>
 */
class VoipPacket : public ::omnetpp::cPacket
{
  protected:
    unsigned int IDtalk;
    unsigned int nframes;
    unsigned int IDframe;
    ::omnetpp::simtime_t timestamp;
    ::omnetpp::simtime_t arrivalTime;
    ::omnetpp::simtime_t playoutTime;
    unsigned int size;

  private:
    void copy(const VoipPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VoipPacket&);

  public:
    VoipPacket(const char *name=nullptr, short kind=0);
    VoipPacket(const VoipPacket& other);
    virtual ~VoipPacket();
    VoipPacket& operator=(const VoipPacket& other);
    virtual VoipPacket *dup() const override {return new VoipPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getIDtalk() const;
    virtual void setIDtalk(unsigned int IDtalk);
    virtual unsigned int getNframes() const;
    virtual void setNframes(unsigned int nframes);
    virtual unsigned int getIDframe() const;
    virtual void setIDframe(unsigned int IDframe);
    virtual ::omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(::omnetpp::simtime_t timestamp);
    virtual ::omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(::omnetpp::simtime_t arrivalTime);
    virtual ::omnetpp::simtime_t getPlayoutTime() const;
    virtual void setPlayoutTime(::omnetpp::simtime_t playoutTime);
    virtual unsigned int getSize() const;
    virtual void setSize(unsigned int size);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VoipPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VoipPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __VOIPPACKET_M_H

